//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsFinalSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public string DeliveryID { get; set; }
        public string AID { get; set; }
        public string OID { get; set; }
        public string GoodsStatus { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual GoodOrder GoodOrder { get; set; }
    }
}
