//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsFinalSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDetail
    {
        public string ImportID { get; set; }
        public string GID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Import Import { get; set; }
    }
}
