//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsFinalSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ItemImported
    {
        public string GID { get; set; }
        public string ImportID { get; set; }
        public string GName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    }
}
